-- SarkariScout Phone Server - Direct MySQL Schema
-- Generated from prisma/schema.prisma

CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(36) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `passwordHash` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191),
  `role` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
  `emailVerifiedAt` DATETIME(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_key` (`email`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `profiles` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `educationLevel` VARCHAR(191),
  `degrees` TEXT,
  `state` VARCHAR(191),
  `district` VARCHAR(191),
  `languages` TEXT,
  `category` ENUM('GEN', 'OBC', 'SC', 'ST', 'EWS'),
  `dob` DATETIME(3),
  `gender` VARCHAR(191),
  `phone` VARCHAR(191),
  `examFamilies` TEXT,
  `preferredStates` TEXT,
  `preferredPosts` TEXT,
  `keywords` TEXT,
  `experience` TEXT,
  `notifyInstant` BOOLEAN NOT NULL DEFAULT true,
  `notifyDigest` BOOLEAN NOT NULL DEFAULT true,
  `digestTime` VARCHAR(191) NOT NULL DEFAULT '09:05',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `profiles_userId_key` (`userId`),
  CONSTRAINT `profiles_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sources` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `type` ENUM('NCS_API', 'RSS', 'HTML', 'PDF') NOT NULL,
  `baseUrl` VARCHAR(191) NOT NULL,
  `schedule` VARCHAR(191) NOT NULL DEFAULT '0 */6 * * *',
  `lastRunAt` DATETIME(3),
  `lastRunStatus` VARCHAR(191),
  `lastRunMessage` VARCHAR(191),
  `itemsPerRun` INT NOT NULL DEFAULT 0,
  `totalItems` INT NOT NULL DEFAULT 0,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `configJson` TEXT,
  `selectorsJson` TEXT,
  `headersJson` TEXT,
  `rateLimitMs` INT NOT NULL DEFAULT 1000,
  `retryCount` INT NOT NULL DEFAULT 3,
  `errorMessage` TEXT,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` VARCHAR(36) NOT NULL,
  `fingerprint` VARCHAR(191) NOT NULL,
  `sourceId` VARCHAR(36),
  `sourceUrl` VARCHAR(191),
  `org` VARCHAR(191) NOT NULL,
  `advtNo` VARCHAR(191),
  `title` VARCHAR(191) NOT NULL,
  `postNames` TEXT,
  `totalVacancies` INT,
  `state` VARCHAR(191) NOT NULL DEFAULT 'ALL_IN',
  `district` VARCHAR(191),
  `category` ENUM('GOVERNMENT', 'SEMI_GOVERNMENT', 'PSU', 'BANKING', 'RAILWAY', 'DEFENCE', 'POLICE', 'TEACHING', 'MEDICAL', 'ENGINEERING', 'IT', 'PRIVATE', 'INTERNSHIP', 'TRAINING', 'CONTRACT') NOT NULL DEFAULT 'GOVERNMENT',
  `examFamily` VARCHAR(191),
  `qualificationText` TEXT,
  `qualificationLevels` TEXT,
  `ageMin` INT,
  `ageMax` INT,
  `gender` VARCHAR(191) DEFAULT 'ALL',
  `categoryFeesJson` TEXT,
  `generalFee` INT,
  `obcFee` INT,
  `scStFee` INT,
  `applyStart` DATETIME(3),
  `applyEnd` DATETIME(3),
  `feeEnd` DATETIME(3),
  `feePaymentEnd` DATETIME(3),
  `examDate` DATETIME(3),
  `examEndDate` DATETIME(3),
  `admitCardDate` DATETIME(3),
  `resultDate` DATETIME(3),
  `interviewDate` DATETIME(3),
  `status` ENUM('OPEN', 'CLOSED', 'REVIEW') NOT NULL DEFAULT 'OPEN',
  `notificationPdfUrl` VARCHAR(191),
  `applyUrl` VARCHAR(191),
  `applyUrlPost` VARCHAR(191),
  `officialNotificationUrl` VARCHAR(191),
  `officialUrls` TEXT,
  `eligibilityCriteria` TEXT,
  `howToApply` TEXT,
  `selectionProcess` TEXT,
  `examPattern` TEXT,
  `syllabus` TEXT,
  `importantDates` TEXT,
  `contactInfo` TEXT,
  `sourceUrlHash` VARCHAR(191),
  `rawHtml` TEXT,
  `rawHash` VARCHAR(191),
  `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `jobs_fingerprint_key` (`fingerprint`),
  INDEX `jobs_status_idx` (`status`),
  INDEX `jobs_rawHash_idx` (`rawHash`),
  INDEX `jobs_sourceId_idx` (`sourceId`),
  INDEX `jobs_state_idx` (`state`),
  INDEX `jobs_district_idx` (`district`),
  INDEX `jobs_applyEnd_idx` (`applyEnd`),
  INDEX `jobs_category_idx` (`category`),
  INDEX `jobs_examFamily_idx` (`examFamily`),
  INDEX `jobs_feePaymentEnd_idx` (`feePaymentEnd`),
  CONSTRAINT `jobs_sourceId_fkey` FOREIGN KEY (`sourceId`) REFERENCES `sources`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `job_changes` (
  `id` VARCHAR(36) NOT NULL,
  `jobId` VARCHAR(36) NOT NULL,
  `type` ENUM('EXAM_DATE', 'VENUE', 'DEADLINE', 'CORRIGENDUM', 'RESULT', 'ADMIT_CARD') NOT NULL,
  `field` VARCHAR(191) NOT NULL,
  `before` TEXT,
  `after` TEXT,
  `detectedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `notified` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `job_changes_jobId_idx` (`jobId`),
  INDEX `job_changes_detectedAt_idx` (`detectedAt`),
  CONSTRAINT `job_changes_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_jobs` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `jobId` VARCHAR(36) NOT NULL,
  `applied` BOOLEAN NOT NULL DEFAULT false,
  `appliedAt` DATETIME(3),
  `notes` TEXT,
  `stage` ENUM('APPLIED', 'EXAM', 'ADMIT_CARD', 'RESULT', 'REJECTED', 'SELECTED'),
  `examCity` VARCHAR(191),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_jobs_userId_jobId_key` (`userId`, `jobId`),
  INDEX `user_jobs_userId_idx` (`userId`),
  INDEX `user_jobs_stage_idx` (`stage`),
  CONSTRAINT `user_jobs_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `user_jobs_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notification_logs` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `jobId` VARCHAR(36),
  `type` ENUM('DIGEST', 'INSTANT', 'WELCOME', 'CHANGE_ALERT', 'VERIFICATION', 'PASSWORD_RESET') NOT NULL,
  `channel` VARCHAR(191) NOT NULL DEFAULT 'email',
  `subject` VARCHAR(191),
  `sentAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `status` VARCHAR(191) NOT NULL DEFAULT 'sent',
  `openedAt` DATETIME(3),
  `clickedAt` DATETIME(3),
  `bounced` BOOLEAN NOT NULL DEFAULT false,
  `unsubscribed` BOOLEAN NOT NULL DEFAULT false,
  PRIMARY KEY (`id`),
  INDEX `notification_logs_userId_idx` (`userId`),
  INDEX `notification_logs_jobId_idx` (`jobId`),
  INDEX `notification_logs_sentAt_idx` (`sentAt`),
  INDEX `notification_logs_type_idx` (`type`),
  CONSTRAINT `notification_logs_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `notification_logs_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `jobs`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `email_preferences` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `digestEnabled` BOOLEAN NOT NULL DEFAULT true,
  `digestTime` VARCHAR(191) NOT NULL DEFAULT '09:05',
  `instantEnabled` BOOLEAN NOT NULL DEFAULT false,
  `weeklyEnabled` BOOLEAN NOT NULL DEFAULT true,
  `unsubscribeToken` VARCHAR(191) NOT NULL,
  `unsubscribedAt` DATETIME(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_preferences_userId_key` (`userId`),
  UNIQUE KEY `email_preferences_unsubscribeToken_key` (`unsubscribeToken`),
  CONSTRAINT `email_preferences_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `crawl_logs` (
  `id` VARCHAR(36) NOT NULL,
  `sourceId` VARCHAR(36) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'running',
  `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `finishedAt` DATETIME(3),
  `itemsFound` INT NOT NULL DEFAULT 0,
  `itemsNew` INT NOT NULL DEFAULT 0,
  `itemsUpdated` INT NOT NULL DEFAULT 0,
  `errorMessage` TEXT,
  `duration` INT,
  PRIMARY KEY (`id`),
  INDEX `crawl_logs_sourceId_idx` (`sourceId`),
  INDEX `crawl_logs_startedAt_idx` (`startedAt`),
  INDEX `crawl_logs_status_idx` (`status`),
  CONSTRAINT `crawl_logs_sourceId_fkey` FOREIGN KEY (`sourceId`) REFERENCES `sources`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `subscriptions` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `plan` VARCHAR(191) NOT NULL DEFAULT 'FREE',
  `status` VARCHAR(191) NOT NULL DEFAULT 'active',
  `razorpayOrderId` VARCHAR(191),
  `startsAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `endsAt` DATETIME(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `subscriptions_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `audit_logs` (
  `id` VARCHAR(36) NOT NULL,
  `action` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191),
  `ip` VARCHAR(45),
  `userAgent` TEXT,
  `method` VARCHAR(10),
  `url` TEXT,
  `status` INT,
  `duration` INT,
  `meta` TEXT,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `audit_logs_userId_idx` (`userId`),
  INDEX `audit_logs_createdAt_idx` (`createdAt`),
  INDEX `audit_logs_action_idx` (`action`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `error_logs` (
  `id` VARCHAR(36) NOT NULL,
  `level` VARCHAR(191) NOT NULL DEFAULT 'error',
  `message` TEXT NOT NULL,
  `stack` TEXT,
  `method` VARCHAR(10),
  `url` VARCHAR(500),
  `status` INT,
  `userId` VARCHAR(191),
  `ip` VARCHAR(45),
  `userAgent` TEXT,
  `causedBy` TEXT,
  `meta` TEXT,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `error_logs_level_idx` (`level`),
  INDEX `error_logs_createdAt_idx` (`createdAt`),
  INDEX `error_logs_userId_idx` (`userId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `user_documents` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `type` ENUM('PHOTO', 'SIGNATURE', 'MARKSHEET', 'CERTIFICATE', 'ID_PROOF', 'ADDRESS_PROOF', 'CATEGORY_CERT', 'EXPERIENCE', 'OTHER') NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `fileName` VARCHAR(191) NOT NULL,
  `filePath` VARCHAR(191) NOT NULL,
  `fileSize` INT NOT NULL,
  `mimeType` VARCHAR(191) NOT NULL,
  `isDefault` BOOLEAN NOT NULL DEFAULT false,
  `metadata` TEXT,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_documents_userId_idx` (`userId`),
  INDEX `user_documents_type_idx` (`type`),
  CONSTRAINT `user_documents_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `bug_reports` (
  `id` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(191),
  `title` VARCHAR(191) NOT NULL,
  `description` TEXT NOT NULL,
  `category` VARCHAR(191) NOT NULL DEFAULT 'bug',
  `priority` VARCHAR(191) NOT NULL DEFAULT 'medium',
  `status` ENUM('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED') NOT NULL DEFAULT 'OPEN',
  `adminNotes` TEXT,
  `resolvedAt` DATETIME(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `bug_reports_userId_idx` (`userId`),
  INDEX `bug_reports_status_idx` (`status`),
  INDEX `bug_reports_createdAt_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mock_tests` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `description` TEXT,
  `examFamily` VARCHAR(191) NOT NULL,
  `qualification` VARCHAR(191),
  `totalQuestions` INT NOT NULL,
  `totalMarks` INT NOT NULL,
  `durationMinutes` INT NOT NULL,
  `isPublished` BOOLEAN NOT NULL DEFAULT false,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mock_tests_examFamily_idx` (`examFamily`),
  INDEX `mock_tests_isPublished_idx` (`isPublished`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mock_questions` (
  `id` VARCHAR(36) NOT NULL,
  `testId` VARCHAR(36) NOT NULL,
  `questionText` TEXT NOT NULL,
  `optionA` VARCHAR(191) NOT NULL,
  `optionB` VARCHAR(191) NOT NULL,
  `optionC` VARCHAR(191) NOT NULL,
  `optionD` VARCHAR(191) NOT NULL,
  `correctOption` VARCHAR(191) NOT NULL,
  `explanation` TEXT,
  `marks` INT NOT NULL DEFAULT 1,
  `sortOrder` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `mock_questions_testId_idx` (`testId`),
  CONSTRAINT `mock_questions_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `mock_tests`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `mock_test_attempts` (
  `id` VARCHAR(36) NOT NULL,
  `testId` VARCHAR(36) NOT NULL,
  `userId` VARCHAR(36) NOT NULL,
  `score` INT,
  `totalAnswered` INT,
  `correctCount` INT,
  `timeTakenSec` INT,
  `answers` TEXT,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `mock_test_attempts_testId_idx` (`testId`),
  INDEX `mock_test_attempts_userId_idx` (`userId`),
  INDEX `mock_test_attempts_createdAt_idx` (`createdAt`),
  CONSTRAINT `mock_test_attempts_testId_fkey` FOREIGN KEY (`testId`) REFERENCES `mock_tests`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `mock_test_attempts_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `previous_papers` (
  `id` VARCHAR(36) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `examFamily` VARCHAR(191) NOT NULL,
  `year` INT NOT NULL,
  `qualification` VARCHAR(191),
  `fileUrl` VARCHAR(191),
  `externalUrl` VARCHAR(191),
  `description` TEXT,
  `downloadCount` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `previous_papers_examFamily_idx` (`examFamily`),
  INDEX `previous_papers_year_idx` (`year`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
