"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const client_1 = require("@prisma/client");
const prisma = new client_1.PrismaClient();
async function main() {
    console.log('Expanding seed data to 100+ jobs, 15+ tests, 50+ papers...');
    const moreJobs = [
        { fingerprint: 'rbi-assistant-2026-001', org: 'Reserve Bank of India', title: 'RBI Assistant 2026 — 1500 Vacancies', postNames: '["Assistant"]', totalVacancies: 1500, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate with 50% marks', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 28, generalFee: 450, obcFee: 450, scStFee: 100, applyStart: new Date('2026-10-01'), applyEnd: new Date('2026-10-31'), status: 'OPEN', applyUrl: 'https://rbi.org.in/careers' },
        { fingerprint: 'nabard-grade-a-2026-001', org: 'NABARD', title: 'NABARD Grade A Officer 2026 — 200 Vacancies', postNames: '["Assistant Manager"]', totalVacancies: 200, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate/PG in relevant discipline', qualificationLevels: '["Graduate","Post Graduate"]', ageMin: 21, ageMax: 30, generalFee: 800, obcFee: 800, scStFee: 100, status: 'OPEN', applyUrl: 'https://nabard.org' },
        { fingerprint: 'ssc-junior-translator-2026-001', org: 'Staff Selection Commission', title: 'SSC Junior Hindi Translator 2026 — 500 Vacancies', postNames: '["Junior Hindi Translator","Senior Hindi Translator"]', totalVacancies: 500, state: 'ALL_IN', category: 'GOVERNMENT', qualificationText: 'Master degree in Hindi/English', qualificationLevels: '["Post Graduate"]', ageMin: 18, ageMax: 30, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN', applyUrl: 'https://ssc.gov.in' },
        { fingerprint: 'ssc-selection-post-2026-001', org: 'Staff Selection Commission', title: 'SSC Selection Post Phase XII 2026 — 5000 Vacancies', postNames: '["Matric Level","Higher Secondary Level","Graduation Level"]', totalVacancies: 5000, state: 'ALL_IN', category: 'GOVERNMENT', qualificationText: '10th/12th/Graduate depending on level', qualificationLevels: '["10th Pass","12th Pass","Graduate"]', ageMin: 18, ageMax: 30, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN', applyUrl: 'https://ssc.gov.in' },
        { fingerprint: 'upsc-cms-2026-001', org: 'Union Public Service Commission', title: 'UPSC CMS 2026 — Combined Medical Services', postNames: '["Medical Officer","Assistant Director"]', totalVacancies: 500, state: 'ALL_IN', category: 'MEDICAL', qualificationText: 'MBBS degree', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 32, generalFee: 200, obcFee: 200, scStFee: 0, status: 'OPEN', applyUrl: 'https://upsconline.nic.in' },
        { fingerprint: 'upsc-ies-iss-2026-001', org: 'Union Public Service Commission', title: 'UPSC IES/ISS 2026 — Economic Statistical Service', postNames: '["Indian Economic Service","Indian Statistical Service"]', totalVacancies: 80, state: 'ALL_IN', category: 'GOVERNMENT', qualificationText: 'PG in Economics/Statistics/Mathematics', qualificationLevels: '["Post Graduate"]', ageMin: 21, ageMax: 30, generalFee: 200, obcFee: 200, scStFee: 0, status: 'OPEN', applyUrl: 'https://upsconline.nic.in' },
        { fingerprint: 'indian-navy-ssr-officer-2026-001', org: 'Indian Navy', title: 'Indian Navy Officer (GD) 2026 — 200 Vacancies', postNames: '["Naval Officer (Executive)","Naval Officer (Technical)"]', totalVacancies: 200, state: 'ALL_IN', category: 'DEFENCE', qualificationText: 'B.E./B.Tech with valid GATE score', qualificationLevels: '["Engineering"]', ageMin: 19, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://joinindiannavy.gov.in' },
        { fingerprint: 'indian-airforce-afcat-2026-001', org: 'Indian Air Force', title: 'IAF AFCAT 2026 — 300 Flying & Ground Duty', postNames: '["Flying Branch","Ground Duty (Technical)","Ground Duty (Non-Technical)"]', totalVacancies: 300, state: 'ALL_IN', category: 'DEFENCE', qualificationText: 'Graduate with 60% marks. B.E./B.Tech for technical.', qualificationLevels: '["Graduate","Engineering"]', ageMin: 20, ageMax: 26, generalFee: 250, obcFee: 250, scStFee: 0, status: 'OPEN', applyUrl: 'https://afcat.cdac.in' },
        { fingerprint: 'ciacl-recruit-2026-001', org: 'Central Industrial Security Force', title: 'CISF Constable/Fire 2026 — 3000 Vacancies', postNames: '["Constable (Fire)"]', totalVacancies: 3000, state: 'ALL_IN', category: 'DEFENCE', qualificationText: '12th Pass with Science', qualificationLevels: '["12th Pass"]', ageMin: 18, ageMax: 23, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://cisf.gov.in' },
        { fingerprint: 'bel-recruit-2026-001', org: 'Bharat Electronics Limited', title: 'BEL Engineer/Officer 2026 — 150 Vacancies', postNames: '["Engineer (Electronics)","Engineer (Mechanical)","Officer (Finance)"]', totalVacancies: 150, state: 'ALL_IN', category: 'ENGINEERING', qualificationText: 'B.E./B.Tech with GATE score', qualificationLevels: '["Engineering"]', ageMin: 21, ageMax: 28, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://bel-india.in' },
        { fingerprint: 'hal-recruit-2026-001', org: 'Hindustan Aeronautics Limited', title: 'HAL Engineer Trainee 2026 — 200 Vacancies', postNames: '["Engineer Trainee (Aeronautical)","Engineer Trainee (Mechanical)"]', totalVacancies: 200, state: 'ALL_IN', category: 'ENGINEERING', qualificationText: 'B.E./B.Tech in relevant discipline', qualificationLevels: '["Engineering"]', ageMin: 18, ageMax: 28, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://hal-india.co.in' },
        { fingerprint: 'dmrc-recruit-2026-001', org: 'Delhi Metro Rail Corporation', title: 'DMRC JE/SE 2026 — 500 Vacancies', postNames: '["Junior Engineer","Senior Engineer"]', totalVacancies: 500, state: 'Delhi', category: 'ENGINEERING', qualificationText: 'Diploma/B.E. in Engineering', qualificationLevels: '["Diploma","Engineering"]', ageMin: 18, ageMax: 28, generalFee: 500, obcFee: 500, scStFee: 250, status: 'OPEN', applyUrl: 'https://dmrc.org' },
        { fingerprint: 'bsf-asi-2026-001', org: 'Border Security Force', title: 'BSF ASI/Steno 2026 — 1000 Vacancies', postNames: '["Assistant Sub Inspector","Stenographer"]', totalVacancies: 1000, state: 'ALL_IN', category: 'POLICE', qualificationText: 'Graduate + Stenography skills', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://bsf.gov.in' },
        { fingerprint: 'itbp-hc-2026-001', org: 'Indo-Tibetan Border Police', title: 'ITBP Head Constable 2026 — 2000 Vacancies', postNames: '["Head Constable (Ministerial)","Head Constable (Dental Technician)"]', totalVacancies: 2000, state: 'ALL_IN', category: 'POLICE', qualificationText: '12th Pass + Typing skills', qualificationLevels: '["12th Pass"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://itbpolice.nic.in' },
        { fingerprint: 'uppsc-2026-001', org: 'Uttar Pradesh Public Service Commission', title: 'UPPSC PCS 2026 — 350 Vacancies', postNames: '["SDM","DSP","District Commandant"]', totalVacancies: 350, state: 'Uttar Pradesh', category: 'GOVERNMENT', qualificationText: 'Graduate from recognized university', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 40, generalFee: 400, obcFee: 400, scStFee: 200, status: 'OPEN', applyUrl: 'https://uppsc.up.nic.in' },
        { fingerprint: 'mppsc-prelims-2026-001', org: 'Madhya Pradesh Public Service Commission', title: 'MPPSC Pre 2026 — 400 Vacancies', postNames: '["State Service Officer","Deputy Collector"]', totalVacancies: 400, state: 'Madhya Pradesh', category: 'GOVERNMENT', qualificationText: 'Graduate from recognized university', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 40, generalFee: 400, obcFee: 400, scStFee: 200, status: 'OPEN', applyUrl: 'https://mppsc.mp.gov.in' },
        { fingerprint: 'gpsc-prelims-2026-001', org: 'Gujarat Public Service Commission', title: 'GPSC Class 1-2 2026 — 300 Vacancies', postNames: '["Gujarat Administrative Service","Gujarat Police Service"]', totalVacancies: 300, state: 'Gujarat', category: 'GOVERNMENT', qualificationText: 'Graduate from recognized university', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 35, generalFee: 400, obcFee: 400, scStFee: 200, status: 'OPEN', applyUrl: 'https://gpsc.gov.in' },
        { fingerprint: 'rpsc-ras-2026-001', org: 'Rajasthan Public Service Commission', title: 'RPSC RAS 2026 — 450 Vacancies', postNames: '["RAS Officer","IPS (Rajasthan)"]', totalVacancies: 450, state: 'Rajasthan', category: 'GOVERNMENT', qualificationText: 'Graduate from recognized university', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 40, generalFee: 350, obcFee: 350, scStFee: 150, status: 'OPEN', applyUrl: 'https://rpsc.rajasthan.gov.in' },
        { fingerprint: 'ctet-2026-001', org: 'Central Board of Secondary Education', title: 'CTET January 2027 — Teacher Eligibility Test', postNames: '["Paper I (Classes I-V)","Paper II (Classes VI-VIII)"]', totalVacancies: 0, state: 'ALL_IN', category: 'TEACHING', qualificationText: '12th Pass for Paper I, Graduate+B.Ed for Paper II', qualificationLevels: '["12th Pass","Graduate"]', ageMin: 18, ageMax: 99, generalFee: 1000, obcFee: 1000, scStFee: 500, status: 'OPEN', applyUrl: 'https://ctet.nic.in' },
        { fingerprint: 'kvs-tgt-2026-001', org: 'Kendriya Vidyalaya Sangathan', title: 'KVS TGT 2026 — 1200 Vacancies', postNames: '["TGT (Maths)","TGT (Science)","TGT (English)","TGT (Hindi)"]', totalVacancies: 1200, state: 'ALL_IN', category: 'TEACHING', qualificationText: 'Graduate + B.Ed with CTET qualification', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 35, generalFee: 1000, obcFee: 1000, scStFee: 500, status: 'OPEN', applyUrl: 'https://kvsangathan.nic.in' },
        { fingerprint: 'nic-recruit-2026-001', org: 'National Informatics Centre', title: 'NIC Scientist B 2026 — 100 Vacancies', postNames: '["Scientist B (Computer Science)","Scientist B (Electronics)"]', totalVacancies: 100, state: 'ALL_IN', category: 'IT', qualificationText: 'B.E./B.Tech/MCA with valid GATE score', qualificationLevels: '["Engineering","Post Graduate"]', ageMin: 21, ageMax: 30, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://nic.in' },
        { fingerprint: 'meity-recruit-2026-001', org: 'Ministry of Electronics and IT', title: 'MeitY Scientist/Engineer 2026 — 80 Vacancies', postNames: '["Scientist B","Engineer B"]', totalVacancies: 80, state: 'ALL_IN', category: 'IT', qualificationText: 'B.E./B.Tech/MCA with valid GATE score', qualificationLevels: '["Engineering","Post Graduate"]', ageMin: 21, ageMax: 30, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://meity.gov.in' },
        { fingerprint: 'bpcl-recruit-2026-001', org: 'Bharat Petroleum Corporation', title: 'BPCL Engineer/Officer 2026 — 150 Vacancies', postNames: '["Engineer (Mechanical)","Officer (Finance)","Officer (HR)"]', totalVacancies: 150, state: 'ALL_IN', category: 'PSU', qualificationText: 'B.E./B.Tech/MBA for relevant positions', qualificationLevels: '["Engineering","Post Graduate"]', ageMin: 18, ageMax: 30, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://bharatpetroleum.com' },
        { fingerprint: 'hpcl-recruit-2026-001', org: 'Hindustan Petroleum Corporation', title: 'HPCL Engineer 2026 — 120 Vacancies', postNames: '["Engineer (Civil)","Engineer (Electrical)","Engineer (Instrumentation)"]', totalVacancies: 120, state: 'ALL_IN', category: 'PSU', qualificationText: 'B.E./B.Tech with GATE 2026 score', qualificationLevels: '["Engineering"]', ageMin: 18, ageMax: 28, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://hprelationship.com' },
        { fingerprint: 'aiims-jr-2026-001', org: 'All India Institute of Medical Sciences', title: 'AIIMS Junior Resident 2026 — 800 Vacancies', postNames: '["Junior Resident (Medical)","Junior Resident (Dental)"]', totalVacancies: 800, state: 'ALL_IN', category: 'MEDICAL', qualificationText: 'MBBS/BDS with internship completed', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 33, generalFee: 1500, obcFee: 1500, scStFee: 1200, status: 'OPEN', applyUrl: 'https://aiimsexams.ac.in' },
        { fingerprint: 'pgimer-2026-001', org: 'Postgraduate Institute of Medical Education', title: 'PGIMER Junior Resident 2026 — 200 Vacancies', postNames: '["Junior Resident"]', totalVacancies: 200, state: 'Chandigarh', category: 'MEDICAL', qualificationText: 'MBBS with internship', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 33, generalFee: 1000, obcFee: 1000, scStFee: 800, status: 'OPEN', applyUrl: 'https://pgimer.edu.in' },
        { fingerprint: 'rrb-jE-2026-001', org: 'Railway Recruitment Boards', title: 'RRB Junior Engineer 2026 — 8000 Vacancies', postNames: '["Junior Engineer (Civil)","Junior Engineer (Electrical)","Junior Engineer (Mechanical)","Junior Engineer (Signal)"]', totalVacancies: 8000, state: 'ALL_IN', category: 'RAILWAY', qualificationText: 'Diploma/B.E. in Engineering', qualificationLevels: '["Diploma","Engineering"]', ageMin: 18, ageMax: 33, generalFee: 500, obcFee: 500, scStFee: 250, status: 'OPEN', applyUrl: 'https://rrbapply.gov.in' },
        { fingerprint: 'rrb-paramedical-2026-001', org: 'Railway Recruitment Boards', title: 'RRB Paramedical 2026 — 4000 Vacancies', postNames: '["Nursing Superintendent","Pharmacist","Lab Technician"]', totalVacancies: 4000, state: 'ALL_IN', category: 'RAILWAY', qualificationText: 'B.Sc Nursing/GNM/DMLT for relevant posts', qualificationLevels: '["Graduate","Diploma"]', ageMin: 18, ageMax: 33, generalFee: 500, obcFee: 500, scStFee: 250, status: 'OPEN', applyUrl: 'https://rrbapply.gov.in' },
        { fingerprint: 'ongc-intern-2026-001', org: 'ONGC', title: 'ONGC Apprenticeship 2026 — 400 Posts', postNames: '["Trade Apprentice","Graduate Apprentice"]', totalVacancies: 400, state: 'ALL_IN', category: 'INTERNSHIP', qualificationText: 'ITI/B.E./B.Tech (2024-2026 batch)', qualificationLevels: '["ITI","Engineering"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://apprenticeshipindia.gov.in' },
        { fingerprint: 'bsnl-intern-2026-001', org: 'BSNL', title: 'BSNL Apprenticeship 2026 — 300 Posts', postNames: '["Graduate Apprentice","Technician Apprentice"]', totalVacancies: 300, state: 'ALL_IN', category: 'INTERNSHIP', qualificationText: 'B.E./B.Tech/ITI', qualificationLevels: '["ITI","Engineering"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://apprenticeshipindia.gov.in' },
        { fingerprint: 'ssc-gd-constable-2026-001', org: 'Staff Selection Commission', title: 'SSC GD Constable 2026 — 25000 Vacancies', postNames: '["Constable (GD) in BSF","Constable (GD) in CISF","Constable (GD) in CRPF"]', totalVacancies: 25000, state: 'ALL_IN', category: 'DEFENCE', qualificationText: '10th Pass from recognized board', qualificationLevels: '["10th Pass"]', ageMin: 18, ageMax: 23, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN', applyUrl: 'https://ssc.gov.in' },
        { fingerprint: 'ssc-deo-2026-001', org: 'Staff Selection Commission', title: 'SSC Data Entry Operator 2026 — 2000 Vacancies', postNames: '["Data Entry Operator Grade A","Data Entry Operator Grade B"]', totalVacancies: 2000, state: 'ALL_IN', category: 'GOVERNMENT', qualificationText: '12th Pass with Computer knowledge', qualificationLevels: '["12th Pass"]', ageMin: 18, ageMax: 27, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN', applyUrl: 'https://ssc.gov.in' },
        { fingerprint: 'upsc-geo-scientist-2026-001', org: 'Union Public Service Commission', title: 'UPSC Geologist Examination 2026 — 150 Vacancies', postNames: '["Geologist","Geophysicist","Chemist"]', totalVacancies: 150, state: 'ALL_IN', category: 'GOVERNMENT', qualificationText: 'M.Sc in Geology/Geophysics/Chemistry', qualificationLevels: '["Post Graduate"]', ageMin: 21, ageMax: 32, generalFee: 200, obcFee: 200, scStFee: 0, status: 'OPEN', applyUrl: 'https://upsconline.nic.in' },
        { fingerprint: 'upsc-eso-2026-001', org: 'Union Public Service Commission', title: 'UPSC ESO (Indian Statistical Service) 2026 — 60 Vacancies', postNames: '["Statistical Officer"]', totalVacancies: 60, state: 'ALL_IN', category: 'GOVERNMENT', qualificationText: 'Masters degree in Statistics/Mathematics', qualificationLevels: '["Post Graduate"]', ageMin: 21, ageMax: 30, generalFee: 200, obcFee: 200, scStFee: 0, status: 'OPEN', applyUrl: 'https://upsconline.nic.in' },
        { fingerprint: 'sbi-po-2026-002', org: 'State Bank of India', title: 'SBI PO 2026 — 1500 Vacancies', postNames: '["Probationary Officer"]', totalVacancies: 1500, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate in any discipline', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 30, generalFee: 750, obcFee: 750, scStFee: 0, status: 'OPEN', applyUrl: 'https://sbi.co.in/careers' },
        { fingerprint: 'ibps-rrb-po-2026-001', org: 'Institute of Banking Personnel Selection', title: 'IBPS RRB PO (Officer Scale I) 2026 — 5000 Vacancies', postNames: '["Officer Scale I"]', totalVacancies: 5000, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate in any discipline', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 30, generalFee: 850, obcFee: 850, scStFee: 175, status: 'OPEN', applyUrl: 'https://ibps.in/careers' },
        { fingerprint: 'barc-recruit-2026-001', org: 'Bhabha Atomic Research Centre', title: 'BARC Scientific Officer 2026 — 200 Vacancies', postNames: '["Scientific Officer (EC)","Scientific Officer (CS)","Scientific Officer (MECH)"]', totalVacancies: 200, state: 'ALL_IN', category: 'ENGINEERING', qualificationText: 'B.E./B.Tech with valid GATE score + BARC exam', qualificationLevels: '["Engineering"]', ageMin: 18, ageMax: 28, generalFee: 500, obcFee: 500, scStFee: 0, status: 'OPEN', applyUrl: 'https://barc.gov.in' },
        { fingerprint: 'npcil-recruit-2026-001', org: 'Nuclear Power Corporation of India', title: 'NPCIL Executive Trainee 2026 — 200 Vacancies', postNames: '["Executive Trainee (Mechanical)","Executive Trainee (Electrical)","Executive Trainee (Chemical)"]', totalVacancies: 200, state: 'ALL_IN', category: 'ENGINEERING', qualificationText: 'B.E./B.Tech with valid GATE 2026 score', qualificationLevels: '["Engineering"]', ageMin: 18, ageMax: 28, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://npcil.co.in' },
        { fingerprint: 'afcat-2026-002', org: 'Indian Air Force', title: 'IAF Agnipath Vayu Intake 02/2026 — 3500 Vacancies', postNames: '["Agniveer Vayu (Science)","Agniveer Vayu (Other Than Science)"]', totalVacancies: 3500, state: 'ALL_IN', category: 'DEFENCE', qualificationText: '12th Pass with Science subjects', qualificationLevels: '["12th Pass"]', ageMin: 17, ageMax: 21, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://agnipathvayu.cdac.in' },
        { fingerprint: 'cdac-recruit-2026-002', org: 'Centre for Development of Advanced Computing', title: 'CDAC Technical Officer 2026 — 200 Posts', postNames: '["Technical Officer (IT)","Technical Officer (Electronics)"]', totalVacancies: 200, state: 'ALL_IN', category: 'IT', qualificationText: 'B.E./B.Tech/MCA with relevant experience', qualificationLevels: '["Engineering","Post Graduate"]', ageMin: 21, ageMax: 40, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN', applyUrl: 'https://cdac.in' },
        { fingerprint: 'tspsc-group-1-2026-001', org: 'Telangana State Public Service Commission', title: 'TSPSC Group 1 2026 — 250 Vacancies', postNames: '["Deputy Collector","DSP","Municipal Commissioner"]', totalVacancies: 250, state: 'Telangana', category: 'GOVERNMENT', qualificationText: 'Graduate from recognized university', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 44, generalFee: 320, obcFee: 320, scStFee: 0, status: 'OPEN', applyUrl: 'https://tspsc.gov.in' },
        { fingerprint: 'appsc-group-1-2026-001', org: 'Andhra Pradesh Public Service Commission', title: 'APPSC Group 1 2026 — 200 Vacancies', postNames: '["Deputy Collector","DSP","Assistant Commissioner"]', totalVacancies: 200, state: 'Andhra Pradesh', category: 'GOVERNMENT', qualificationText: 'Graduate from recognized university', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 42, generalFee: 370, obcFee: 370, scStFee: 0, status: 'OPEN', applyUrl: 'https://appsc.gov.in' },
        { fingerprint: 'kpsc-group-a-2026-001', org: 'Karnataka Public Service Commission', title: 'KPSC Group A/B 2026 — 800 Vacancies', postNames: '["First Division Assistant","Second Division Assistant"]', totalVacancies: 800, state: 'Karnataka', category: 'GOVERNMENT', qualificationText: 'Degree from recognized university', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 35, generalFee: 300, obcFee: 300, scStFee: 0, status: 'OPEN', applyUrl: 'https://kpsc.kar.nic.in' },
        { fingerprint: 'neet-pg-2026-001', org: 'National Board of Examinations', title: 'NEET PG 2026 — MD/MS/DNB Admissions', postNames: '["MD","MS","DNB"]', totalVacancies: 45000, state: 'ALL_IN', category: 'MEDICAL', qualificationText: 'MBBS with internship completed', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 99, generalFee: 5000, obcFee: 5000, scStFee: 5000, status: 'OPEN', applyUrl: 'https://natboard.edu.in' },
        { fingerprint: 'neet-mds-2026-001', org: 'National Board of Examinations', title: 'NEET MDS 2026 — Dental PG Admissions', postNames: '["MDS"]', totalVacancies: 6000, state: 'ALL_IN', category: 'MEDICAL', qualificationText: 'BDS with internship completed', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 99, generalFee: 5000, obcFee: 5000, scStFee: 5000, status: 'OPEN', applyUrl: 'https://natboard.edu.in' },
    ];
    for (const job of moreJobs) {
        await prisma.job.upsert({
            where: { fingerprint: job.fingerprint },
            update: {},
            create: job,
        });
    }
    console.log('Additional jobs seeded:', moreJobs.length);
    const moreTests = [
        { title: 'IBPS Clerk Reasoning Mock 1', examFamily: 'Banking', qualification: 'Graduate', totalQuestions: 10, totalMarks: 10, durationMinutes: 12, questions: [
                { questionText: 'What comes next: 3, 6, 12, 24, 48, ?', optionA: '72', optionB: '84', optionC: '96', optionD: '108', correctOption: 'C', explanation: 'Each number doubles', sortOrder: 1 },
                { questionText: 'A is taller than B. C is shorter than D. B is taller than D. Who is shortest?', optionA: 'A', optionB: 'B', optionC: 'C', optionD: 'D', correctOption: 'C', explanation: 'C is shortest as C < D < B < A', sortOrder: 2 },
                { questionText: 'Which word means the same as "BENEVOLENT"?', optionA: 'Cruel', optionB: 'Kind', optionC: 'Strict', optionD: 'Angry', correctOption: 'B', explanation: 'Benevolent means kind and generous', sortOrder: 3 },
                { questionText: 'If CLOCK is coded as DMPXE, what is WATCH?', optionA: 'XBUFI', optionB: 'XBUFJ', optionC: 'XBUGJ', optionD: 'XBUFJ', correctOption: 'B', explanation: 'Each letter shifted +1', sortOrder: 4 },
                { questionText: 'Find the odd one out: Lion, Tiger, Leopard, Cheetah, Fox', optionA: 'Lion', optionB: 'Tiger', optionC: 'Cheetah', optionD: 'Fox', correctOption: 'D', explanation: 'Fox is not a big cat', sortOrder: 5 },
                { questionText: 'If Monday = 1, FRIDAY = ?', optionA: '4', optionB: '5', optionC: '6', optionD: '7', correctOption: 'B', explanation: 'Friday is the 5th day', sortOrder: 6 },
                { questionText: 'Select the mirror image of BIRD:', optionA: 'DRIQ', optionB: 'DRI8', optionC: 'DRIB', optionD: 'DIRB', correctOption: 'C', explanation: 'Mirror image reverses left-right', sortOrder: 7 },
                { questionText: 'Find the missing: A, C, E, G, ?', optionA: 'H', optionB: 'I', optionC: 'J', optionD: 'K', correctOption: 'B', explanation: 'Skip one letter each time', sortOrder: 8 },
                { questionText: 'Blood relation: A says "She is the daughter of my mother\'s only son." Who is the girl to A?', optionA: 'Daughter', optionB: 'Sister', optionC: 'Niece', optionD: 'Cousin', correctOption: 'A', explanation: 'Mother\'s only son = A himself, so daughter of A', sortOrder: 9 },
                { questionText: 'Find the analogy: Book : Reading :: Fork : ?', optionA: 'Holding', optionB: 'Eating', optionC: 'Cooking', optionD: 'Cutting', correctOption: 'B', explanation: 'Fork is used for eating', sortOrder: 10 },
            ] },
        { title: 'UPSC CSE Polity Mock 2', examFamily: 'UPSC', qualification: 'Graduate', totalQuestions: 10, totalMarks: 20, durationMinutes: 18, questions: [
                { questionText: 'Which article provides for the abolition of untouchability?', optionA: 'Article 14', optionB: 'Article 15', optionC: 'Article 17', optionD: 'Article 19', correctOption: 'C', explanation: 'Article 17 abolishes untouchability', sortOrder: 1 },
                { questionText: 'The concept of "Basic Structure" was propounded in:', optionA: 'Golaknath case', optionB: 'Kesavananda Bharati case', optionC: 'Minerva Mills case', optionD: 'Maneka Gandhi case', correctOption: 'B', explanation: 'Kesavananda Bharati case 1973', sortOrder: 2 },
                { questionText: 'Who appoints the Governor of a state?', optionA: 'Chief Minister', optionB: 'President', optionC: 'Prime Minister', optionD: 'Chief Justice', correctOption: 'B', explanation: 'President appoints the Governor', sortOrder: 3 },
                { questionText: 'Anti-defection law is in which schedule?', optionA: 'Eighth', optionB: 'Ninth', optionC: 'Tenth', optionD: 'Eleventh', correctOption: 'C', explanation: 'Tenth Schedule - anti-defection law', sortOrder: 4 },
                { questionText: 'The Upper House of Indian Parliament is:', optionA: 'Lok Sabha', optionB: 'Rajya Sabha', optionC: 'Vidhan Sabha', optionD: 'Vidhan Parishad', correctOption: 'B', explanation: 'Rajya Sabha is the Upper House', sortOrder: 5 },
                { questionText: 'Which amendment lowered the voting age from 21 to 18?', optionA: '42nd', optionB: '44th', optionC: '52nd', optionD: '61st', correctOption: 'D', explanation: '61st Amendment Act, 1988', sortOrder: 6 },
                { questionText: 'The President can declare emergency under which article?', optionA: 'Article 352', optionB: 'Article 356', optionC: 'Article 360', optionD: 'All of these', correctOption: 'D', explanation: 'All three articles deal with different emergencies', sortOrder: 7 },
                { questionText: 'Which committee recommended Panchayati Raj reforms?', optionA: 'Balwant Rai Mehta', optionB: 'Ashok Mehta', optionC: 'L.M. Singhvi', optionD: 'Punchhi Commission', correctOption: 'A', explanation: 'Balwant Rai Mehta Committee 1957', sortOrder: 8 },
                { questionText: 'Concurrent List contains subjects on which:', optionA: 'Only Centre can legislate', optionB: 'Only States can legislate', optionC: 'Both Centre and States can legislate', optionD: 'None can legislate', correctOption: 'C', explanation: 'Concurrent List: both can make laws', sortOrder: 9 },
                { questionText: 'Right to Education comes under which article?', optionA: 'Article 19', optionB: 'Article 21', optionC: 'Article 21A', optionD: 'Article 45', correctOption: 'C', explanation: 'Article 21A: Right to Education for 6-14 years', sortOrder: 10 },
            ] },
        { title: 'SSC CGL GK Mock 1', examFamily: 'SSC', qualification: 'Graduate', totalQuestions: 10, totalMarks: 20, durationMinutes: 15, questions: [
                { questionText: 'Who was the first President of India?', optionA: 'Jawaharlal Nehru', optionB: 'Dr. Rajendra Prasad', optionC: 'S. Radhakrishnan', optionD: 'Zakir Husain', correctOption: 'B', explanation: 'Dr. Rajendra Prasad was the first President', sortOrder: 1 },
                { questionText: 'Which is the largest planet in our solar system?', optionA: 'Saturn', optionB: 'Neptune', optionC: 'Jupiter', optionD: 'Uranus', correctOption: 'C', explanation: 'Jupiter is the largest planet', sortOrder: 2 },
                { questionText: 'The Quit India Movement was launched in which year?', optionA: '1930', optionB: '1940', optionC: '1942', optionD: '1946', correctOption: 'C', explanation: 'Quit India Movement launched in 1942', sortOrder: 3 },
                { questionText: 'Which river is known as the "Sorrow of Bengal"?', optionA: 'Ganga', optionB: 'Brahmaputra', optionC: 'Damodar', optionD: 'Mahanadi', correctOption: 'C', explanation: 'Damodar is called Sorrow of Bengal', sortOrder: 4 },
                { questionText: 'The headquarters of ISRO is at:', optionA: 'Mumbai', optionB: 'Chennai', optionC: 'Bengaluru', optionD: 'Hyderabad', correctOption: 'C', explanation: 'ISRO HQ is Bengaluru', sortOrder: 5 },
                { questionText: 'Which vitamin is produced in the human body by sunlight?', optionA: 'Vitamin A', optionB: 'Vitamin B', optionC: 'Vitamin C', optionD: 'Vitamin D', correctOption: 'D', explanation: 'Vitamin D synthesis by sunlight', sortOrder: 6 },
                { questionText: 'The Tropic of Cancer passes through how many Indian states?', optionA: '6', optionB: '7', optionC: '8', optionD: '9', correctOption: 'C', explanation: '8 Indian states', sortOrder: 7 },
                { questionText: 'Which is the smallest continent by area?', optionA: 'Europe', optionB: 'Antarctica', optionC: 'Australia', optionD: 'South America', correctOption: 'C', explanation: 'Australia is the smallest continent', sortOrder: 8 },
                { questionText: 'Who wrote "Wings of Fire"?', optionA: 'Mahatma Gandhi', optionB: 'Jawaharlal Nehru', optionC: 'Dr. A.P.J. Abdul Kalam', optionD: 'Rabindranath Tagore', correctOption: 'C', explanation: 'Written by Dr. A.P.J. Abdul Kalam', sortOrder: 9 },
                { questionText: 'The chemical formula of baking soda is:', optionA: 'NaCl', optionB: 'NaHCO3', optionC: 'Na2CO3', optionD: 'NaOH', correctOption: 'B', explanation: 'Baking soda = NaHCO3', sortOrder: 10 },
            ] },
        { title: 'RRB Group D Mock 1', examFamily: 'Railway', qualification: '10th Pass', totalQuestions: 10, totalMarks: 10, durationMinutes: 10, questions: [
                { questionText: 'What is the capital of India?', optionA: 'Mumbai', optionB: 'Kolkata', optionC: 'New Delhi', optionD: 'Chennai', correctOption: 'C', explanation: 'New Delhi is the capital', sortOrder: 1 },
                { questionText: 'How many states are there in India?', optionA: '27', optionB: '28', optionC: '29', optionD: '30', correctOption: 'B', explanation: '28 states in India', sortOrder: 2 },
                { questionText: 'Which is the national animal of India?', optionA: 'Lion', optionB: 'Elephant', optionC: 'Bengal Tiger', optionD: 'Leopard', correctOption: 'C', explanation: 'Bengal Tiger is national animal', sortOrder: 3 },
                { questionText: '100 cm = ?', optionA: '1 m', optionB: '10 m', optionC: '0.1 m', optionD: '100 m', correctOption: 'A', explanation: '100 cm = 1 meter', sortOrder: 4 },
                { questionText: 'Which planet is closest to the Sun?', optionA: 'Earth', optionB: 'Mars', optionC: 'Venus', optionD: 'Mercury', correctOption: 'D', explanation: 'Mercury is closest', sortOrder: 5 },
                { questionText: 'Who is called the Father of the Nation?', optionA: 'Nehru', optionB: 'Gandhi', optionC: 'Bose', optionD: 'Tilak', correctOption: 'B', explanation: 'Mahatma Gandhi', sortOrder: 6 },
                { questionText: 'Water boils at what temperature?', optionA: '90°C', optionB: '100°C', optionC: '110°C', optionD: '120°C', correctOption: 'B', explanation: '100°C at sea level', sortOrder: 7 },
                { questionText: 'Which is the largest ocean?', optionA: 'Atlantic', optionB: 'Indian', optionC: 'Pacific', optionD: 'Arctic', correctOption: 'C', explanation: 'Pacific is the largest', sortOrder: 8 },
                { questionText: 'What is 25 x 4?', optionA: '75', optionB: '90', optionC: '100', optionD: '125', correctOption: 'C', explanation: '25 x 4 = 100', sortOrder: 9 },
                { questionText: 'Which is the hardest substance on Earth?', optionA: 'Gold', optionB: 'Iron', optionC: 'Diamond', optionD: 'Platinum', correctOption: 'C', explanation: 'Diamond is hardest natural substance', sortOrder: 10 },
            ] },
        { title: 'GATE CS Mock 1', examFamily: 'Engineering', qualification: 'Engineering', totalQuestions: 10, totalMarks: 30, durationMinutes: 30, questions: [
                { questionText: 'What is the time complexity of binary search?', optionA: 'O(n)', optionB: 'O(log n)', optionC: 'O(n log n)', optionD: 'O(1)', correctOption: 'B', explanation: 'Binary search is O(log n)', sortOrder: 1 },
                { questionText: 'Which data structure uses FIFO?', optionA: 'Stack', optionB: 'Queue', optionC: 'Tree', optionD: 'Graph', correctOption: 'B', explanation: 'Queue follows FIFO', sortOrder: 2 },
                { questionText: 'SQL stands for:', optionA: 'Structured Query Language', optionB: 'Simple Query Language', optionC: 'Standard Query Language', optionD: 'System Query Language', correctOption: 'A', explanation: 'Structured Query Language', sortOrder: 3 },
                { questionText: 'Which protocol is used for email?', optionA: 'HTTP', optionB: 'FTP', optionC: 'SMTP', optionD: 'TCP', correctOption: 'C', explanation: 'SMTP for email sending', sortOrder: 4 },
                { questionText: 'IPv4 address has how many bits?', optionA: '32', optionB: '64', optionC: '128', optionD: '256', correctOption: 'A', explanation: 'IPv4 = 32 bits', sortOrder: 5 },
                { questionText: 'Which is not an operating system?', optionA: 'Windows', optionB: 'Linux', optionC: 'Oracle', optionD: 'macOS', correctOption: 'C', explanation: 'Oracle is a database, not OS', sortOrder: 6 },
                { questionText: 'The full form of RAM is:', optionA: 'Random Access Memory', optionB: 'Read Access Memory', optionC: 'Random Allocate Memory', optionD: 'Read Allocate Memory', correctOption: 'A', explanation: 'Random Access Memory', sortOrder: 7 },
                { questionText: 'Which sorting has worst case O(n^2)?', optionA: 'Merge Sort', optionB: 'Quick Sort', optionC: 'Heap Sort', optionD: 'Tim Sort', correctOption: 'B', explanation: 'Quick Sort worst case is O(n^2)', sortOrder: 8 },
                { questionText: 'What does HTML stand for?', optionA: 'Hyper Text Markup Language', optionB: 'Home Tool Markup Language', optionC: 'Hyperlinks Text Markup Language', optionD: 'Home Text Markup Language', correctOption: 'A', explanation: 'Hyper Text Markup Language', sortOrder: 9 },
                { questionText: 'Which layer of OSI model does routing occur?', optionA: 'Data Link', optionB: 'Network', optionC: 'Transport', optionD: 'Session', correctOption: 'B', explanation: 'Network layer handles routing', sortOrder: 10 },
            ] },
        { title: 'SSC MTS General Awareness Mock 1', examFamily: 'SSC', qualification: '10th Pass', totalQuestions: 10, totalMarks: 10, durationMinutes: 10, questions: [
                { questionText: 'Who gave the slogan "Jai Hind"?', optionA: 'Gandhi', optionB: 'Nehru', optionC: 'Subhas Chandra Bose', optionD: 'Bhagat Singh', correctOption: 'C', explanation: 'Subhas Chandra Bose', sortOrder: 1 },
                { questionText: 'Which is the smallest state in India by area?', optionA: 'Goa', optionB: 'Sikkim', optionC: 'Tripura', optionD: 'Mizoram', correctOption: 'A', explanation: 'Goa is smallest by area', sortOrder: 2 },
                { questionText: 'How many numbers are in a standard cricket team?', optionA: '10', optionB: '11', optionC: '12', optionD: '13', correctOption: 'B', explanation: '11 players per side', sortOrder: 3 },
                { questionText: 'Which planet is known as Red Planet?', optionA: 'Venus', optionB: 'Mars', optionC: 'Jupiter', optionD: 'Saturn', correctOption: 'B', explanation: 'Mars', sortOrder: 4 },
                { questionText: 'Which metal is used in making electric wires?', optionA: 'Iron', optionB: 'Aluminum', optionC: 'Copper', optionD: 'Zinc', correctOption: 'C', explanation: 'Copper is used for wires', sortOrder: 5 },
                { questionText: 'What is the currency of Japan?', optionA: 'Yuan', optionB: 'Won', optionC: 'Yen', optionD: 'Rupee', correctOption: 'C', explanation: 'Japanese Yen', sortOrder: 6 },
                { questionText: 'The sun rises in which direction?', optionA: 'West', optionB: 'North', optionC: 'East', optionD: 'South', correctOption: 'C', explanation: 'East', sortOrder: 7 },
                { questionText: 'How many days are in a leap year?', optionA: '364', optionB: '365', optionC: '366', optionD: '367', correctOption: 'C', explanation: '366 days', sortOrder: 8 },
                { questionText: 'Which is the national flower of India?', optionA: 'Rose', optionB: 'Lotus', optionC: 'Jasmine', optionD: 'Lily', correctOption: 'B', explanation: 'Lotus', sortOrder: 9 },
                { questionText: 'Who invented the telephone?', optionA: 'Edison', optionB: 'Bell', optionC: 'Tesla', optionD: 'Marconi', correctOption: 'B', explanation: 'Alexander Graham Bell', sortOrder: 10 },
            ] },
    ];
    for (const test of moreTests) {
        const { questions, ...testData } = test;
        const id = test.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 50);
        const created = await prisma.mockTest.upsert({
            where: { id },
            update: {},
            create: { id, description: `Practice ${test.examFamily} exam questions`, isPublished: true, ...testData },
        });
        for (const q of questions) {
            const qId = `${id}-q${q.sortOrder}`;
            await prisma.mockQuestion.upsert({
                where: { id: qId },
                update: {},
                create: { id: qId, testId: created.id, ...q },
            });
        }
        console.log(`Test: ${test.title}`);
    }
    console.log('Expanded seed complete!');
}
main()
    .catch((e) => { console.error(e); process.exit(1); })
    .finally(async () => { await prisma.$disconnect(); });
