"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const client_1 = require("@prisma/client");
const prisma = new client_1.PrismaClient();
async function main() {
    console.log('Massive expansion: 200+ jobs, 20+ tests, 100+ papers...');
    const extraJobs = [
        { fingerprint: 'bppsc-69th-2026', org: 'Bihar Public Service Commission', title: 'BPSC 69th CCE — 800 Vacancies', postNames: '["SDM","DSP","District Fire Officer"]', totalVacancies: 800, state: 'Bihar', category: 'GOVERNMENT', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 37, generalFee: 750, obcFee: 750, scStFee: 200, status: 'OPEN' },
        { fingerprint: 'ukpsc-rostam-2026', org: 'Uttarakhand Public Service Commission', title: 'UKPSC PCS 2026 — 200 Vacancies', postNames: '["SDM","DSP"]', totalVacancies: 200, state: 'Uttar Pradesh', category: 'GOVERNMENT', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 42, generalFee: 350, obcFee: 350, scStFee: 150, status: 'OPEN' },
        { fingerprint: 'jpsc-68th-2026', org: 'Jharkhand Public Service Commission', title: 'JPSC 68th CCE — 350 Vacancies', postNames: '["Deputy Collector","DSP"]', totalVacancies: 350, state: 'Jharkhand', category: 'GOVERNMENT', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 40, generalFee: 600, obcFee: 600, scStFee: 150, status: 'OPEN' },
        { fingerprint: 'opsc-odisha-2026', org: 'Odisha Public Service Commission', title: 'OPSC OCS 2026 — 300 Vacancies', postNames: '["IAS (Odisha)","IPS (Odisha)"]', totalVacancies: 300, state: 'Odisha', category: 'GOVERNMENT', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 38, generalFee: 500, obcFee: 500, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'wbpsc-2026', org: 'West Bengal Public Service Commission', title: 'WBPSC WBCS 2026 — 500 Vacancies', postNames: '["Executive","Police","Revenue"]', totalVacancies: 500, state: 'West Bengal', category: 'GOVERNMENT', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 36, generalFee: 320, obcFee: 320, scStFee: 80, status: 'OPEN' },
        { fingerprint: 'hpsc-hcs-2026', org: 'Haryana Public Service Commission', title: 'Haryana Civil Services 2026 — 200 Vacancies', postNames: '["SDM","DSP","Tehsildar"]', totalVacancies: 200, state: 'Haryana', category: 'GOVERNMENT', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 42, generalFee: 1000, obcFee: 250, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'hppsc-2026', org: 'Himachal Pradesh Public Service Commission', title: 'HPPSC HPAS 2026 — 150 Vacancies', postNames: '["SDM","DSP"]', totalVacancies: 150, state: 'Himachal Pradesh', category: 'GOVERNMENT', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 45, generalFee: 400, obcFee: 100, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'tnpsc-group1-2026', org: 'Tamil Nadu Public Service Commission', title: 'TNPSC Group 1 2026 — 180 Vacancies', postNames: '["Deputy Collector","DSP"]', totalVacancies: 180, state: 'Tamil Nadu', category: 'GOVERNMENT', qualificationText: 'Degree', qualificationLevels: '["Graduate"]', ageMin: 21, ageMax: 36, generalFee: 250, obcFee: 250, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'bob-po-2026', org: 'Bank of Baroda', title: 'Bank of Baroda PO 2026 — 500 Vacancies', postNames: '["Probationary Officer"]', totalVacancies: 500, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 28, generalFee: 600, obcFee: 600, scStFee: 100, status: 'OPEN' },
        { fingerprint: 'ubi-clerk-2026', org: 'Union Bank of India', title: 'UBI Clerk 2026 — 1200 Vacancies', postNames: '["Customer Service Associate"]', totalVacancies: 1200, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 28, generalFee: 590, obcFee: 590, scStFee: 118, status: 'OPEN' },
        { fingerprint: 'iob-po-2026', org: 'Indian Overseas Bank', title: 'IOB PO 2026 — 400 Vacancies', postNames: '["Probationary Officer"]', totalVacancies: 400, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 28, generalFee: 590, obcFee: 590, scStFee: 118, status: 'OPEN' },
        { fingerprint: 'central-bank-clerk-2026', org: 'Central Bank of India', title: 'Central Bank Clerk 2026 — 1000 Vacancies', postNames: '["Sub Staff"]', totalVacancies: 1000, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 28, generalFee: 590, obcFee: 590, scStFee: 118, status: 'OPEN' },
        { fingerprint: 'canara-bank-po-2026', org: 'Canara Bank', title: 'Canara Bank PO 2026 — 800 Vacancies', postNames: '["PO (Manipal Programme)"]', totalVacancies: 800, state: 'ALL_IN', category: 'BANKING', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 28, generalFee: 700, obcFee: 700, scStFee: 135, status: 'OPEN' },
        { fingerprint: 'ssc-steno-2026', org: 'Staff Selection Commission', title: 'SSC Stenographer 2026 — 1500 Vacancies', postNames: '["Steno Grade C","Steno Grade D"]', totalVacancies: 1500, state: 'ALL_IN', category: 'GOVERNMENT', qualificationText: '12th Pass', qualificationLevels: '["12th Pass"]', ageMin: 18, ageMax: 27, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'ssc-cpo-2026', org: 'Staff Selection Commission', title: 'SSC CPO 2026 — 5000 Vacancies', postNames: '["Sub Inspector (Delhi Police)","Sub Inspector (CAPFs)"]', totalVacancies: 5000, state: 'ALL_IN', category: 'DEFENCE', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 20, ageMax: 25, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'ssc-je-2026', org: 'Staff Selection Commission', title: 'SSC Junior Engineer 2026 — 2000 Vacancies', postNames: '["JE (Civil)","JE (Electrical)","JE (Mechanical)"]', totalVacancies: 2000, state: 'ALL_IN', category: 'ENGINEERING', qualificationText: 'Diploma/B.E. in Engineering', qualificationLevels: '["Diploma","Engineering"]', ageMin: 18, ageMax: 32, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'rrb-ntpc-2026', org: 'Railway Recruitment Boards', title: 'RRB NTPC Graduate 2026 — 10000 Vacancies', postNames: '["Station Master","Goods Guard","Traffic Apprentice"]', totalVacancies: 10000, state: 'ALL_IN', category: 'RAILWAY', qualificationText: 'Graduate', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 33, generalFee: 500, obcFee: 500, scStFee: 250, status: 'OPEN' },
        { fingerprint: 'rrb-alp-2026', org: 'Railway Recruitment Boards', title: 'RRB ALP 2026 — 6000 Vacancies', postNames: '["Assistant Loco Pilot"]', totalVacancies: 6000, state: 'ALL_IN', category: 'RAILWAY', qualificationText: 'ITI/Diploma in relevant trade', qualificationLevels: '["ITI","Diploma"]', ageMin: 18, ageMax: 28, generalFee: 500, obcFee: 500, scStFee: 250, status: 'OPEN' },
        { fingerprint: 'bsf-hc-2026', org: 'Border Security Force', title: 'BSF Head Constable Ministerial 2026 — 1500 Vacancies', postNames: '["Head Constable (Ministerial)"]', totalVacancies: 1500, state: 'ALL_IN', category: 'DEFENCE', qualificationText: '12th Pass + Typing', qualificationLevels: '["12th Pass"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'crpf-hc-2026', org: 'Central Reserve Police Force', title: 'CRPF ASI/Steno 2026 — 2000 Vacancies', postNames: '["ASI (Steno)","ASI (Ministerial)"]', totalVacancies: 2000, state: 'ALL_IN', category: 'DEFENCE', qualificationText: 'Graduate + Steno/Typing', qualificationLevels: '["Graduate"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'ssb-hc-2026', org: 'Sashastra Seema Bal', title: 'SSB Head Constable 2026 — 1200 Vacancies', postNames: '["Head Constable (Ministerial)","Head Constable (Veterinary)"]', totalVacancies: 1200, state: 'ALL_IN', category: 'DEFENCE', qualificationText: '12th/Graduate', qualificationLevels: '["12th Pass","Graduate"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'ongc-ae-2026', org: 'Oil and Natural Gas Corporation', title: 'ONGC AEE 2026 — 300 Vacancies', postNames: '["AEE (Drilling)","AEE (Production)","AEE (Mechanical)"]', totalVacancies: 300, state: 'ALL_IN', category: 'PSU', qualificationText: 'B.E./B.Tech + GATE', qualificationLevels: '["Engineering"]', ageMin: 18, ageMax: 28, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'ntpc-recruit-2026', org: 'NTPC Limited', title: 'NTPC Executive Trainee 2026 — 250 Vacancies', postNames: '["ET (Mechanical)","ET (Electrical)","ET (Civil)"]', totalVacancies: 250, state: 'ALL_IN', category: 'PSU', qualificationText: 'B.E./B.Tech + GATE', qualificationLevels: '["Engineering"]', ageMin: 18, ageMax: 27, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'pgcil-2026', org: 'Power Grid Corporation of India', title: 'PGCIL Diploma Trainee 2026 — 400 Vacancies', postNames: '["Diploma Trainee (Civil)","Diploma Trainee (Electrical)"]', totalVacancies: 400, state: 'ALL_IN', category: 'PSU', qualificationText: '3-year Diploma in Engineering', qualificationLevels: '["Diploma"]', ageMin: 18, ageMax: 27, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'isro-recruit-2026', org: 'Indian Space Research Organisation', title: 'ISRO Scientist/Engineer 2026 — 150 Vacancies', postNames: '["Scientist/Engineer SD","Scientist/Engineer SC"]', totalVacancies: 150, state: 'ALL_IN', category: 'IT', qualificationText: 'B.E./B.Tech/M.E./M.Tech', qualificationLevels: '["Engineering","Post Graduate"]', ageMin: 18, ageMax: 28, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'drdo-recruit-2026', org: 'Defence Research and Development Organisation', title: 'DRDO Scientist B 2026 — 200 Vacancies', postNames: '["Scientist B (CSE)","Scientist B (ECE)","Scientist B (MECH)"]', totalVacancies: 200, state: 'ALL_IN', category: 'IT', qualificationText: 'B.E./B.Tech + GATE', qualificationLevels: '["Engineering"]', ageMin: 21, ageMax: 28, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'dsssb-pgt-2026', org: 'Delhi Subordinate Services Board', title: 'DSSSB PGT 2026 — 1000 Vacancies', postNames: '["PGT (Hindi)","PGT (English)","PGT (Maths)","PGT (Science)"]', totalVacancies: 1000, state: 'Delhi', category: 'TEACHING', qualificationText: 'Post Graduate + B.Ed', qualificationLevels: '["Post Graduate"]', ageMin: 18, ageMax: 36, generalFee: 100, obcFee: 100, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'kvs-pgt-2026', org: 'Kendriya Vidyalaya Sangathan', title: 'KVS PGT 2026 — 600 Vacancies', postNames: '["PGT (Computer Science)","PGT (Physics)","PGT (Chemistry)"]', totalVacancies: 600, state: 'ALL_IN', category: 'TEACHING', qualificationText: 'Post Graduate + B.Ed + CTET', qualificationLevels: '["Post Graduate"]', ageMin: 18, ageMax: 35, generalFee: 1000, obcFee: 1000, scStFee: 500, status: 'OPEN' },
        { fingerprint: 'nta-ugc-net-2026', org: 'National Testing Agency', title: 'NTA UGC-NET Dec 2026 — Assistant Professor/JRF', postNames: '["Assistant Professor","Junior Research Fellowship"]', totalVacancies: 0, state: 'ALL_IN', category: 'TEACHING', qualificationText: 'Post Graduate', qualificationLevels: '["Post Graduate"]', ageMin: 18, ageMax: 30, generalFee: 1150, obcFee: 600, scStFee: 325, status: 'OPEN' },
        { fingerprint: 'aiims-nursing-2026', org: 'All India Institute of Medical Sciences', title: 'AIIMS Nursing Officer 2026 — 3000 Vacancies', postNames: '["Nursing Officer (Staff Nurse Grade II)"]', totalVacancies: 3000, state: 'ALL_IN', category: 'MEDICAL', qualificationText: 'B.Sc Nursing/GNM', qualificationLevels: '["Graduate","Diploma"]', ageMin: 18, ageMax: 35, generalFee: 1500, obcFee: 1500, scStFee: 1200, status: 'OPEN' },
        { fingerprint: 'esic-sr-resident-2026', org: 'Employees State Insurance Corporation', title: 'ESIC Senior Resident 2026 — 500 Vacancies', postNames: '["Senior Resident"]', totalVacancies: 500, state: 'ALL_IN', category: 'MEDICAL', qualificationText: 'MBBS + MD/MS/DNB', qualificationLevels: '["Post Graduate"]', ageMin: 18, ageMax: 40, generalFee: 500, obcFee: 500, scStFee: 250, status: 'OPEN' },
        { fingerprint: 'npcil-intern-2026', org: 'NPCIL', title: 'NPCIL Apprenticeship 2026 — 200 Posts', postNames: '["Graduate Apprentice","Technician Apprentice"]', totalVacancies: 200, state: 'ALL_IN', category: 'INTERNSHIP', qualificationText: 'B.E./B.Tech/ITI', qualificationLevels: '["ITI","Engineering"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
        { fingerprint: 'iocl-intern-2026', org: 'Indian Oil Corporation', title: 'IOCL Apprenticeship 2026 — 500 Posts', postNames: '["Trade Apprentice","Graduate Apprentice"]', totalVacancies: 500, state: 'ALL_IN', category: 'INTERNSHIP', qualificationText: 'ITI/B.E./B.Tech', qualificationLevels: '["ITI","Engineering"]', ageMin: 18, ageMax: 25, generalFee: 0, obcFee: 0, scStFee: 0, status: 'OPEN' },
    ];
    for (const job of extraJobs) {
        await prisma.job.upsert({ where: { fingerprint: job.fingerprint }, update: {}, create: job });
    }
    console.log('Extra jobs seeded:', extraJobs.length);
    const extraTests = [
        { title: 'SSC CGL Quantitative Aptitude', examFamily: 'SSC', qualification: 'Graduate', totalQuestions: 10, totalMarks: 20, durationMinutes: 15, questions: [
                { questionText: 'What is 15% of 200?', optionA: '25', optionB: '30', optionC: '35', optionD: '40', correctOption: 'B', explanation: '15/100 × 200 = 30', sortOrder: 1 },
                { questionText: 'If A:B = 3:5 and B:C = 2:3, then A:B:C = ?', optionA: '6:10:15', optionB: '3:5:8', optionC: '5:3:2', optionD: '6:5:3', correctOption: 'A', explanation: 'LCM of 5,2 = 10. A=6, B=10, C=15', sortOrder: 2 },
                { questionText: 'A train 200m long crosses a pole in 20 sec. Speed?', optionA: '36 km/h', optionB: '40 km/h', optionC: '30 km/h', optionD: '45 km/h', correctOption: 'A', explanation: '200/20 = 10 m/s = 36 km/h', sortOrder: 3 },
                { questionText: 'Simple interest on Rs.5000 at 8% for 3 years?', optionA: 'Rs.1000', optionB: 'Rs.1200', optionC: 'Rs.1500', optionD: 'Rs.800', correctOption: 'B', explanation: '5000 × 8 × 3 / 100 = 1200', sortOrder: 4 },
                { questionText: '√(144 + 25) = ?', optionA: '12', optionB: '13', optionC: '14', optionD: '15', correctOption: 'B', explanation: '√169 = 13', sortOrder: 5 },
                { questionText: 'Average of 5, 10, 15, 20, 25?', optionA: '12', optionB: '15', optionC: '18', optionD: '20', correctOption: 'B', explanation: '(5+10+15+20+25)/5 = 15', sortOrder: 6 },
                { questionText: 'If x + 1/x = 3, then x² + 1/x² = ?', optionA: '5', optionB: '7', optionC: '9', optionD: '11', correctOption: 'B', explanation: '(x+1/x)² = x²+1/x²+2 → 9-2=7', sortOrder: 7 },
                { questionText: '30% of 500 + 20% of 300 = ?', optionA: '200', optionB: '210', optionC: '220', optionD: '230', correctOption: 'B', explanation: '150 + 60 = 210', sortOrder: 8 },
                { questionText: 'A does work in 10 days, B in 15 days. Together in?', optionA: '5 days', optionB: '6 days', optionC: '7 days', optionD: '8 days', correctOption: 'B', explanation: '1/10+1/15 = 5/30 = 1/6 → 6 days', sortOrder: 9 },
                { questionText: 'Ratio of area of circle to square with same perimeter?', optionA: '11:14', optionB: '14:11', optionC: '1:1', optionD: '22:7', correctOption: 'A', explanation: 'Ratio = πr²/(4r²) = π/4 ≈ 11:14', sortOrder: 10 },
            ] },
        { title: 'IBPS PO Reasoning Mock 2', examFamily: 'Banking', qualification: 'Graduate', totalQuestions: 10, totalMarks: 10, durationMinutes: 12, questions: [
                { questionText: 'If in a code SYSTEM = TZUUNF, then BRAIN = ?', optionA: 'CSBJO', optionB: 'CSBJM', optionC: 'CTBJO', optionD: 'CTBJM', correctOption: 'B', explanation: 'Each letter +1', sortOrder: 1 },
                { questionText: 'Find the next: AZ, CX, EV, GT, ?', optionA: 'IQ', optionB: 'IR', optionC: 'JS', optionD: 'JR', correctOption: 'D', explanation: 'Pattern: A+2=C, C+2=E... Z+2=B', sortOrder: 2 },
                { questionText: 'In a queue, A is 7th from front, B is 18th from back, 5 between them. Total?', optionA: '28', optionB: '29', optionC: '30', optionD: '31', correctOption: 'C', explanation: '7+18-1+5 = 29... actually 30', sortOrder: 3 },
                { questionText: 'Pointing to a man, she said: He is son of my mothers only daughter. Who is he?', optionA: 'Brother', optionB: 'Son', optionC: 'Nephew', optionD: 'Father', correctOption: 'B', explanation: 'Mothers only daughter = herself, so son', sortOrder: 4 },
                { questionText: 'Find odd one: 2, 5, 11, 17, 23', optionA: '2', optionB: '5', optionC: '11', optionD: '17', correctOption: 'A', explanation: '2 is only even prime', sortOrder: 5 },
                { questionText: 'A is brother of B. B is sister of C. C is father of D. How is A related to D?', optionA: 'Father', optionB: 'Uncle', optionC: 'Grandfather', optionD: 'Brother', correctOption: 'B', explanation: 'A is Cs brother = Ds uncle', sortOrder: 6 },
                { questionText: 'If MONDAY = 1, what day is 100th day from Monday?', optionA: 'Wednesday', optionB: 'Thursday', optionC: 'Friday', optionD: 'Saturday', correctOption: 'A', explanation: '100 mod 7 = 2, Monday+2 = Wednesday', sortOrder: 7 },
                { questionText: 'Find the missing: J, L, N, P, ?', optionA: 'Q', optionB: 'R', optionC: 'S', optionD: 'T', correctOption: 'B', explanation: 'Skip one letter: J,L,N,P,R', sortOrder: 8 },
                { questionText: 'Statements: All cats are dogs. All dogs are birds. Conclusions: I. All cats are birds. II. All birds are cats.', optionA: 'Only I follows', optionB: 'Only II follows', optionC: 'Both follow', optionD: 'Neither follows', correctOption: 'A', explanation: 'Only I follows by syllogism', sortOrder: 9 },
                { questionText: 'Complete the series: 1, 1, 2, 3, 5, 8, ?', optionA: '11', optionB: '12', optionC: '13', optionD: '14', correctOption: 'C', explanation: 'Fibonacci: 5+8=13', sortOrder: 10 },
            ] },
        { title: 'UPSC CSE Economy Mock', examFamily: 'UPSC', qualification: 'Graduate', totalQuestions: 10, totalMarks: 20, durationMinutes: 18, questions: [
                { questionText: 'Which organisation publishes the World Economic Outlook?', optionA: 'World Bank', optionB: 'IMF', optionC: 'WTO', optionD: 'ADB', correctOption: 'B', explanation: 'IMF publishes WEO', sortOrder: 1 },
                { questionText: 'Fiscal Deficit = ?', optionA: 'Total Expenditure - Total Receipts', optionB: 'Revenue Expenditure - Revenue Receipts', optionC: 'Total Expenditure - Total Receipts excluding borrowings', optionD: 'Capital Expenditure - Capital Receipts', correctOption: 'C', explanation: 'Fiscal deficit = total expenditure - receipts (excl. borrowings)', sortOrder: 2 },
                { questionText: 'What is SLR?', optionA: 'Statutory Liquidity Ratio', optionB: 'Standard Liquidity Ratio', optionC: 'State Liquidity Ratio', optionD: 'Systemic Liquidity Ratio', correctOption: 'A', explanation: 'Statutory Liquidity Ratio', sortOrder: 3 },
                { questionText: 'Which of these is NOT a direct tax?', optionA: 'Income Tax', optionB: 'GST', optionC: 'Corporate Tax', optionD: 'Capital Gains Tax', correctOption: 'B', explanation: 'GST is an indirect tax', sortOrder: 4 },
                { questionText: 'Repo Rate is the rate at which:', optionA: 'Banks lend to each other', optionB: 'RBI lends to banks', optionC: 'Banks lend to public', optionD: 'Government borrows', correctOption: 'B', explanation: 'RBI lends to banks at repo rate', sortOrder: 5 },
                { questionText: 'Which Five Year Plan adopted the objective of "Growth with Social Justice"?', optionA: '7th', optionB: '8th', optionC: '9th', optionD: '10th', correctOption: 'C', explanation: '9th FYP (1997-2002)', sortOrder: 6 },
                { questionText: 'NIFTY 50 is an index of which exchange?', optionA: 'BSE', optionB: 'NSE', optionC: 'MCX', optionD: 'NCDEX', correctOption: 'B', explanation: 'NIFTY 50 is NSE index', sortOrder: 7 },
                { questionText: 'Which is the largest source of revenue for the Indian government?', optionA: 'Corporate Tax', optionB: 'Income Tax', optionC: 'GST', optionD: 'Customs Duty', correctOption: 'C', explanation: 'GST is the largest revenue source', sortOrder: 8 },
                { questionText: 'MUDRA Bank was established under which scheme?', optionA: 'Make in India', optionB: 'Startup India', optionC: 'Standup India', optionD: 'Digital India', correctOption: 'C', explanation: 'Under Pradhan Mantri Mudra Yojana', sortOrder: 9 },
                { questionText: 'What does HDI measure?', optionA: 'Economic growth', optionB: 'Human development', optionC: 'Poverty level', optionD: 'Inflation rate', correctOption: 'B', explanation: 'Human Development Index measures health, education, income', sortOrder: 10 },
            ] },
        { title: 'RRB NTPC GK Mock 1', examFamily: 'Railway', qualification: 'Graduate', totalQuestions: 10, totalMarks: 10, durationMinutes: 10, questions: [
                { questionText: 'Which is the longest river in India?', optionA: 'Yamuna', optionB: 'Ganga', optionC: 'Godavari', optionD: 'Brahmaputra', correctOption: 'B', explanation: 'Ganga is the longest river in India', sortOrder: 1 },
                { questionText: 'Who was the first Prime Minister of India?', optionA: 'Rajendra Prasad', optionB: 'Jawaharlal Nehru', optionC: 'Sardar Patel', optionD: 'Subhas Bose', correctOption: 'B', explanation: 'Jawaharlal Nehru', sortOrder: 2 },
                { questionText: 'The Red Fort is located in?', optionA: 'Mumbai', optionB: 'Kolkata', optionC: 'Delhi', optionD: 'Agra', correctOption: 'C', explanation: 'Red Fort is in Delhi', sortOrder: 3 },
                { questionText: 'Which element has the symbol Fe?', optionA: 'Fluorine', optionB: 'Iron', optionC: 'Francium', optionD: 'Fermium', correctOption: 'B', explanation: 'Fe = Ferrum = Iron', sortOrder: 4 },
                { questionText: 'Indian Railways headquarters is at?', optionA: 'Mumbai', optionB: 'New Delhi', optionC: 'Kolkata', optionD: 'Chennai', correctOption: 'B', explanation: 'Railway Board HQ in New Delhi', sortOrder: 5 },
                { questionText: 'Who wrote "Discovery of India"?', optionA: 'Gandhi', optionB: 'Nehru', optionC: 'Tilak', optionD: 'Ambedkar', correctOption: 'B', explanation: 'Jawaharlal Nehru', sortOrder: 6 },
                { questionText: 'How many zones does Indian Railways have?', optionA: '15', optionB: '16', optionC: '17', optionD: '18', correctOption: 'C', explanation: '17 railway zones', sortOrder: 7 },
                { questionText: 'Which is the busiest railway station in India?', optionA: 'Delhi', optionB: 'Mumbai CST', optionC: 'Howrah', optionD: 'Chennai Central', correctOption: 'B', explanation: 'Mumbai CST is busiest', sortOrder: 8 },
                { questionText: 'First passenger train in India ran between?', optionA: 'Delhi-Agra', optionB: 'Mumbai-Pune', optionC: 'Bombay-Thane', optionD: 'Kolkata-Howrah', correctOption: 'C', explanation: 'Bombay to Thane in 1853', sortOrder: 9 },
                { questionText: 'Which train is called "Queen of Rails"?', optionA: 'Rajdhani', optionB: 'Shatabdi', optionC: 'Palace on Wheels', optionD: 'Deccan Odyssey', correctOption: 'C', explanation: 'Palace on Wheels', sortOrder: 10 },
            ] },
        { title: 'Defence Forces Mock Test', examFamily: 'Defence', qualification: '12th Pass', totalQuestions: 10, totalMarks: 10, durationMinutes: 10, questions: [
                { questionText: 'What does NDA stand for?', optionA: 'National Defence Academy', optionB: 'Naval Defence Academy', optionC: 'National Development Agency', optionD: 'None', correctOption: 'A', explanation: 'National Defence Academy', sortOrder: 1 },
                { questionText: 'Indian Air Force Day is celebrated on?', optionA: 'Jan 15', optionB: 'Oct 8', optionC: 'Dec 4', optionD: 'Aug 15', correctOption: 'B', explanation: 'IAF Day is October 8', sortOrder: 2 },
                { questionText: 'Who is the Supreme Commander of Indian Armed Forces?', optionA: 'Prime Minister', optionB: 'Defence Minister', optionC: 'President', optionD: 'Chief of Defence Staff', correctOption: 'C', explanation: 'President is Supreme Commander', sortOrder: 3 },
                { questionText: 'INS Vikrant is a:', optionA: 'Submarine', optionB: 'Aircraft Carrier', optionC: 'Destroyer', optionD: 'Frigate', correctOption: 'B', explanation: 'INS Vikrant is an aircraft carrier', sortOrder: 4 },
                { questionText: 'How many services does the Indian Armed Forces have?', optionA: '2', optionB: '3', optionC: '4', optionD: '5', correctOption: 'B', explanation: 'Army, Navy, Air Force', sortOrder: 5 },
                { questionText: 'Param Vir Chakra is awarded for:', optionA: 'Gallantry in peacetime', optionB: 'Highest wartime bravery', optionC: 'Distinguished service', optionD: 'Excellence in sports', correctOption: 'B', explanation: 'Highest wartime gallantry award', sortOrder: 6 },
                { questionText: 'Where is the Indian Military Academy located?', optionA: 'Dehradun', optionB: 'Pune', optionC: 'Chennai', optionD: 'Bangalore', correctOption: 'A', explanation: 'IMA is in Dehradun', sortOrder: 7 },
                { questionText: 'Agneepath scheme is for:', optionA: 'Army recruitment', optionB: 'Navy recruitment', optionC: 'Air Force recruitment', optionD: 'All of these', correctOption: 'D', explanation: 'Agnipath is for all three services', sortOrder: 8 },
                { questionText: 'Siachen Glacier is in which range?', optionA: 'Himalayas', optionB: 'Karakoram', optionC: 'Hindukush', optionD: 'Zaskar', correctOption: 'B', explanation: 'Karakoram range', sortOrder: 9 },
                { questionText: 'What is the motto of Indian Army?', optionA: 'Jai Hind', optionB: 'Service Before Self', optionC: 'Touch the Sky with Glory', optionD: 'Defence of India', correctOption: 'B', explanation: 'Service Before Self', sortOrder: 10 },
            ] },
        { title: 'GATE Mechanical Mock 1', examFamily: 'Engineering', qualification: 'Engineering', totalQuestions: 10, totalMarks: 30, durationMinutes: 30, questions: [
                { questionText: 'What is the SI unit of force?', optionA: 'Joule', optionB: 'Pascal', optionC: 'Newton', optionD: 'Watt', correctOption: 'C', explanation: 'Newton (N)', sortOrder: 1 },
                { questionText: 'Carnot cycle efficiency depends on:', optionA: 'Working substance', optionB: 'Temperature limits', optionC: 'Pressure limits', optionD: 'Volume limits', correctOption: 'B', explanation: 'Efficiency = 1 - T2/T1', sortOrder: 2 },
                { questionText: 'Which process has constant pressure?', optionA: 'Isochoric', optionB: 'Isobaric', optionC: 'Isothermal', optionD: 'Adiabatic', correctOption: 'B', explanation: 'Isobaric = constant pressure', sortOrder: 3 },
                { questionText: 'Stress-strain curve for ductile material shows:', optionA: 'Necking region', optionB: 'Elastic region only', optionC: 'Brittle failure', optionD: 'No plastic deformation', correctOption: 'A', explanation: 'Ductile materials show necking', sortOrder: 4 },
                { questionText: 'What is the Bernoulli equation for?', optionA: 'Heat transfer', optionB: 'Fluid flow', optionC: 'Solid mechanics', optionD: 'Thermodynamics', correctOption: 'B', explanation: 'Fluid flow energy conservation', sortOrder: 5 },
                { questionText: 'The purpose of a flywheel is to:', optionA: 'Increase speed', optionB: 'Store energy and reduce speed fluctuation', optionC: 'Reduce power', optionD: 'Increase torque', correctOption: 'B', explanation: 'Flywheel stores rotational energy', sortOrder: 6 },
                { questionText: 'Which bearing supports both radial and thrust loads?', optionA: 'Journal bearing', optionB: 'Ball bearing', optionC: 'Thrust bearing', optionD: 'Plain bearing', correctOption: 'B', explanation: 'Ball bearings handle both loads', sortOrder: 7 },
                { questionText: 'In an IC engine, the crankshaft converts:', optionA: 'Linear to rotary motion', optionB: 'Rotary to linear motion', optionC: 'Heat to work', optionD: 'Pressure to force', correctOption: 'A', explanation: 'Crank converts reciprocating to rotary', sortOrder: 8 },
                { questionText: 'What is the Mach number?', optionA: 'Speed of sound', optionB: 'Ratio of object speed to speed of sound', optionC: 'Speed of light', optionD: 'Reynolds number', correctOption: 'B', explanation: 'Mach = velocity / speed of sound', sortOrder: 9 },
                { questionText: 'Hardness test measures:', optionA: 'Tensile strength', optionB: 'Resistance to indentation', optionC: 'Impact resistance', optionD: 'Fatigue strength', correctOption: 'B', explanation: 'Hardness = resistance to localized plastic deformation', sortOrder: 10 },
            ] },
        { title: 'Police Constable Mock 1', examFamily: 'Police', qualification: '12th Pass', totalQuestions: 10, totalMarks: 10, durationMinutes: 10, questions: [
                { questionText: 'What does FIR stand for?', optionA: 'First Information Report', optionB: 'Federal Investigation Report', optionC: 'First Initial Report', optionD: 'Final Investigation Report', correctOption: 'A', explanation: 'First Information Report under CrPC', sortOrder: 1 },
                { questionText: 'Section 302 of IPC deals with:', optionA: 'Theft', optionB: 'Murder', optionC: 'Assault', optionD: 'Fraud', correctOption: 'B', explanation: 'Section 302: Punishment for murder', sortOrder: 2 },
                { questionText: 'Who files a charge sheet?', optionA: 'Judge', optionB: 'Police', optionC: 'Prosecutor', optionD: 'Complainant', correctOption: 'B', explanation: 'Police files charge sheet after investigation', sortOrder: 3 },
                { questionText: 'What is the full form of CrPC?', optionA: 'Criminal Procedure Code', optionB: 'Central Procedure Code', optionC: 'Civil Procedure Code', optionD: 'Constitutional Procedure Code', correctOption: 'A', explanation: 'Code of Criminal Procedure', sortOrder: 4 },
                { questionText: 'Bail is a matter of right in which offence?', optionA: 'Non-bailable', optionB: 'Bailable', optionC: 'Both', optionD: 'Neither', correctOption: 'B', explanation: 'Bail is a right in bailable offences', sortOrder: 5 },
                { questionText: 'The Indian Penal Code was enacted in:', optionA: '1860', optionB: '1947', optionC: '1950', optionD: '1857', correctOption: 'A', explanation: 'IPC enacted in 1860', sortOrder: 6 },
                { questionText: 'What is the minimum age for police recruitment (constable)?', optionA: '18 years', optionB: '21 years', optionC: '25 years', optionD: '16 years', correctOption: 'A', explanation: 'Minimum 18 years', sortOrder: 7 },
                { questionText: 'Who has the power to grant pardon?', optionA: 'Police', optionB: 'Judge', optionC: 'President/Governor', optionD: 'Advocate', correctOption: 'C', explanation: 'President (Art 72) and Governor (Art 161)', sortOrder: 8 },
                { questionText: 'What is the time limit for filing FIR?', optionA: '24 hours', optionB: '48 hours', optionC: 'No time limit', optionD: '7 days', correctOption: 'C', explanation: 'No time limit for filing FIR', sortOrder: 9 },
                { questionText: 'Zero FIR means:', optionA: 'No FIR filed', optionB: 'FIR filed at any police station regardless of jurisdiction', optionC: 'FIR with zero evidence', optionD: 'Cancelled FIR', correctOption: 'B', explanation: 'Zero FIR can be filed at any station', sortOrder: 10 },
            ] },
        { title: 'NDA Maths Mock 1', examFamily: 'Defence', qualification: '12th Pass', totalQuestions: 10, totalMarks: 20, durationMinutes: 15, questions: [
                { questionText: 'What is the value of sin 30°?', optionA: '1', optionB: '1/2', optionC: '√3/2', optionD: '0', correctOption: 'B', explanation: 'sin 30° = 1/2', sortOrder: 1 },
                { questionText: 'The derivative of x² is:', optionA: 'x', optionB: '2x', optionC: '2x²', optionD: 'x²', correctOption: 'B', explanation: 'd/dx(x²) = 2x', sortOrder: 2 },
                { questionText: 'If A = [1 2; 3 4], what is det(A)?', optionA: '-2', optionB: '2', optionC: '-1', optionD: '1', correctOption: 'A', explanation: 'det = 1×4 - 2×3 = -2', sortOrder: 3 },
                { questionText: 'What is the sum of angles in a triangle?', optionA: '90°', optionB: '180°', optionC: '270°', optionD: '360°', correctOption: 'B', explanation: '180 degrees', sortOrder: 4 },
                { questionText: 'If log₂(8) = x, what is x?', optionA: '2', optionB: '3', optionC: '4', optionD: '8', correctOption: 'B', explanation: '2³ = 8, so x = 3', sortOrder: 5 },
                { questionText: 'What is the integral of 1/x dx?', optionA: 'x²', optionB: 'ln|x| + C', optionC: '1/x²', optionD: 'eˣ', correctOption: 'B', explanation: '∫1/x dx = ln|x| + C', sortOrder: 6 },
                { questionText: 'How many faces does a cube have?', optionA: '4', optionB: '6', optionC: '8', optionD: '12', correctOption: 'B', explanation: '6 faces', sortOrder: 7 },
                { questionText: 'What is the probability of getting heads in a coin toss?', optionA: '0', optionB: '0.25', optionC: '0.5', optionD: '1', correctOption: 'C', explanation: '1/2 = 0.5', sortOrder: 8 },
                { questionText: 'In an AP, if a=2, d=3, what is the 5th term?', optionA: '12', optionB: '14', optionC: '16', optionD: '18', correctOption: 'B', explanation: 'a + 4d = 2 + 12 = 14', sortOrder: 9 },
                { questionText: 'What is the area of a circle with radius 7?', optionA: '44', optionB: '154', optionC: '308', optionD: '616', correctOption: 'B', explanation: 'πr² = 22/7 × 49 = 154', sortOrder: 10 },
            ] },
        { title: 'SSC CHSL Mock 1', examFamily: 'SSC', qualification: '12th Pass', totalQuestions: 10, totalMarks: 20, durationMinutes: 15, questions: [
                { questionText: 'Who invented the World Wide Web?', optionA: 'Bill Gates', optionB: 'Tim Berners-Lee', optionC: 'Steve Jobs', optionD: 'Mark Zuckerberg', correctOption: 'B', explanation: 'Tim Berners-Lee in 1989', sortOrder: 1 },
                { questionText: 'Which gas is used in fire extinguishers?', optionA: 'Oxygen', optionB: 'Nitrogen', optionC: 'CO2', optionD: 'Hydrogen', correctOption: 'C', explanation: 'Carbon dioxide', sortOrder: 2 },
                { questionText: 'The longest bone in the human body is:', optionA: 'Humerus', optionB: 'Femur', optionC: 'Tibia', optionD: 'Fibula', correctOption: 'B', explanation: 'Femur (thigh bone)', sortOrder: 3 },
                { questionText: 'How many players in a hockey team?', optionA: '9', optionB: '10', optionC: '11', optionD: '12', correctOption: 'C', explanation: '11 players', sortOrder: 4 },
                { questionText: 'Which is the hardest natural substance?', optionA: 'Quartz', optionB: 'Topaz', optionC: 'Diamond', optionD: 'Ruby', correctOption: 'C', explanation: 'Diamond', sortOrder: 5 },
                { questionText: 'Photosynthesis occurs in:', optionA: 'Roots', optionB: 'Stems', optionC: 'Leaves', optionD: 'Flowers', correctOption: 'C', explanation: 'Chloroplasts in leaves', sortOrder: 6 },
                { questionText: 'What is the boiling point of water at sea level?', optionA: '90°C', optionB: '95°C', optionC: '100°C', optionD: '105°C', correctOption: 'C', explanation: '100°C', sortOrder: 7 },
                { questionText: 'Which is the largest gland in the human body?', optionA: 'Thyroid', optionB: 'Pancreas', optionC: 'Liver', optionD: 'Kidney', correctOption: 'C', explanation: 'Liver is the largest gland', sortOrder: 8 },
                { questionText: 'Who wrote the Indian National Anthem?', optionA: 'Bankim Chandra', optionB: 'Rabindranath Tagore', optionC: 'Sarojini Naidu', optionD: 'Muhammad Iqbal', correctOption: 'B', explanation: 'Rabindranath Tagore', sortOrder: 9 },
                { questionText: 'Speed of light is approximately:', optionA: '3 × 10⁶ m/s', optionB: '3 × 10⁷ m/s', optionC: '3 × 10⁸ m/s', optionD: '3 × 10⁹ m/s', correctOption: 'C', explanation: '3 × 10⁸ m/s', sortOrder: 10 },
            ] },
    ];
    for (const test of extraTests) {
        const { questions, ...testData } = test;
        const id = test.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 50);
        const created = await prisma.mockTest.upsert({ where: { id }, update: {}, create: { id, description: `Practice ${test.examFamily} exam questions`, isPublished: true, ...testData } });
        for (const q of questions) {
            const qId = `${id}-q${q.sortOrder}`;
            await prisma.mockQuestion.upsert({ where: { id: qId }, update: {}, create: { id: qId, testId: created.id, ...q } });
        }
    }
    console.log('Extra tests seeded:', extraTests.length);
    const extraPapers = [];
    const families = ['SSC CGL', 'SSC CHSL', 'SSC MTS', 'UPSC CSE', 'UPSC CPF', 'IBPS PO', 'IBPS Clerk', 'IBPS RRB', 'SBI PO', 'SBI Clerk', 'RRB NTPC', 'RRB Group D', 'RRB ALP', 'NDA', 'CDS', 'AFCAT', 'CTET', 'GATE CS', 'GATE ME', 'GATE EE'];
    const years = [2023, 2024, 2025];
    const quals = ['10th Pass', '12th Pass', 'Graduate', 'Engineering'];
    let paperCount = 0;
    for (const fam of families) {
        for (const yr of years) {
            const qual = fam.includes('CGL') || fam.includes('PO') || fam.includes('UPSC') ? 'Graduate' : fam.includes('MTS') || fam.includes('Group D') ? '10th Pass' : fam.includes('GATE') ? 'Engineering' : '12th Pass';
            extraPapers.push({
                examFamily: fam, title: `${fam} ${yr} Question Paper`, year: yr, qualification: qual,
                sourceUrl: `https://example.com/${fam.toLowerCase().replace(/\s+/g, '-')}-${yr}`, externalUrl: '', description: `Previous year question paper for ${fam} ${yr}`
            });
            paperCount++;
        }
    }
    for (const paper of extraPapers) {
        const slug = paper.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 60);
        await prisma.previousPaper.upsert({
            where: { id: slug }, update: {},
            create: { id: slug, fileUrl: paper.sourceUrl, downloadCount: Math.floor(Math.random() * 500), ...paper },
        });
    }
    console.log('Extra papers seeded:', extraPapers.length);
    console.log('Massive expansion complete!');
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(async () => { await prisma.$disconnect(); });
